baseURL = 'https://loserwang.github.io/blog'
languageCode = 'zh-cn'
title = '技术笔记'
theme = 'ananke'

[params]
  author = 'loserwang'
  description = '记录学习与技术成长'
  favicon = ''
  site_logo = ''
  recent_posts_number = 5

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 10
  [[menu.main]]
    name = '文章'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 30
